var citiesArray = ["West Union",
  "Lima",
  "Ashland",
  "Jefferson",
  "Athens",
  "Wapakoneta",
  "St Clairsville",
  "Georgetown",
  "Hamilton",
  "Carrollton",
  "Urbana",
  "Springfield",
  "Batavia",
  "Wilmington",
  "Lisbon",
  "Coshocton",
  "Bucyrus",
  "Cleveland",
  "Greenville",
  "Defiance",
  "Delaware",
  "Sandusky",
  "Lancaster",
  "Washington Court House",
  "Columbus",
  "Wauseon",
  "Gallipolis",
  "Chardon",
  "Xenia",
  "Cambridge",
  "Cincinnati",
  "Findlay",
  "Kenton",
  "Cadiz",
  "Napoleon",
  "Hillsboro",
  "Logan",
  "Millersburg",
  "Norwalk",
  "Jackson",
  "Steubenville",
  "Mount Vernon",
  "Painesville",
  "Ironton",
  "Newark",
  "Bellefontaine",
  "Elyria",
  "Toledo",
  "London",
  "Youngstown",
  "Marion",
  "Medina",
  "Pomeroy",
  "Celina",
  "Troy",
  "Woodsfield",
  "Dayton",
  "McConnelsville",
  "Mount Gilead",
  "Zanesville",
  "Caldwell",
  "Port Clinton",
  "Paulding",
  "New Lexington",
  "Circleville",
  "Waverly",
  "Ravenna",
  "Eaton",
  "Ottawa",
  "Mansfield",
  "Chillicothe",
  "Fremont",
  "Portsmouth",
  "Tiffin",
  "Sidney",
  "Canton",
  "Akron",
  "Warren",
  "New Philadelphia",
  "Marysville",
  "Van Wert",
  "McArthur",
  "Lebanon",
  "Marietta",
  "Wooster",
  "Bryan",
  "Bowling Green",
  "Upper Sandusky"
].sort();